#!/usr/bin/make -f

.PHONY: all
all: lint test

.PHONY: test lint fix
test:
	go test ./...

lint:
	go mod tidy -diff
	test ! `goimports -l . | grep .`
	go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...
	go vet ./...
	go run honnef.co/go/tools/cmd/staticcheck@2025.1.1 -checks all ./...
	go run github.com/Antonboom/testifylint@latest ./...

fix:
	go mod tidy
	goimports -w .
	go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
	go run github.com/Antonboom/testifylint@latest -fix ./...
