// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

package nig

import "github.com/gin-gonic/gin"

// New creates a new Manager instance for the given gin router.
//
// Manager provides a runtime approach to dependency injection, using reflection
// to automatically wire dependencies to handler functions based on struct tags.
//
// The g parameter is the gin router (or router group) where handlers will be registered.
//
// Example:
//
//	router := gin.Default()
//	mgr := nig.New(router)
func New(g gin.IRouter) *Manager {
	return &Manager{
		r:    g,
		deps: make(map[string]any),
	}
}

// Manager manages dependencies and handlers using a runtime, reflection-based approach.
//
// It allows you to:
//   - Register dependencies with string keys
//   - Define handler functions that accept *gin.Context and structs with "nig" tags
//   - Automatically wire dependencies to handlers based on struct tags
//
// This approach is more flexible and requires less boilerplate code compared to
// the static Wrapper approach, but uses reflection and may panic at runtime if
// dependencies are misconfigured.
//
// Example workflow:
//
//	// 1. Create manager
//	mgr := nig.New(router)
//
//	// 2. Register dependencies
//	mgr.Register("logger", loggerDep).Register("reqid", reqIDDep)
//
//	// 3. Define handler with tagged struct
//	type HelloArgs struct {
//		Logger zerolog.Logger `nig:"logger"`
//		ReqID  string          `nig:"reqid"`
//	}
//	mgr.GET("/hello", func(c *gin.Context, args HelloArgs) {
//		args.Logger.Info().Str("request_id", args.ReqID).Msg("hello")
//		c.JSON(200, gin.H{"message": "hello"})
//	})
type Manager struct {
	r    gin.IRouter
	deps map[string]any
}

// Register registers a dependency with the given key.
//
// The key is used in struct tags to reference this dependency. The dep parameter
// should be a *Dep[T] instance created with NewDep.
//
// Returns the Manager for method chaining.
//
// Example:
//
//	loggerDep := NewDep(func(c *gin.Context) zerolog.Logger {
//		return log.Logger
//	})
//	mgr.Register("logger", loggerDep)
//
// Then in your handler struct:
//
//	type MyArgs struct {
//		Logger zerolog.Logger `nig:"logger"`
//	}
func (m *Manager) Register(key string, dep any) *Manager {
	m.deps[key] = dep

	// Set the key for Dep[T] instances
	// fail-fast
	dep.(anotherDep).setKey(key)

	return m
}

// prepareHandler create gin-handler and gin-middlewares from user provided handler.
//
// This method will
//
//   - check type of the handler is valid
//   - check if all field has valid struct tag
//   - check if Dep specified by struct tag is registered
//   - check the type of Dep and field is compitable
//   - prepare data (type info, function, ...) which is needed when warpping the handler
//   - warp the handler with codes to create the structs and pass it to the handler
//
// It will panic if the handler cannot pass the checks (fail-fast before starting http server).
//
// The type of user provided handler is restricted to
//
//   - accept *gin.Context and one or more struct
//   - each field in struct is decorated by struct tag
//   - no return value
//
// A conscious example is like:
//
//	type HellowArgs struct { A int `nig:"dep_a"`, ... }
//	func handleHello(c *gin.Context, arg HelloArgs) { ... }
//
// So following handlers is not supported and will panic
//
//	func handleA(c *gin.Context) error            // has return value
//	func handleA(c *gin.Context)                  // no extra struct
//	func handleB(c *gin.Context, ver int)         // not struct
//	func handleC(c *gin.Context, struct{ A int }) // no struct tag
//
// The middlewares is generated by sorting the gin-middlewares defined by Dep.
func (m *Manager) prepareHandler(handler any) (h gin.HandlerFunc, mw []gin.HandlerFunc) {
	// Step 1: Validate handler type
	info, err := validateHandlerType(handler)
	if err != nil {
		panic(err)
	}

	// Step 2: Parse struct tags
	fieldsMap, err := parseStructTags(info.argStructs)
	if err != nil {
		panic(err)
	}

	// Step 3: Validate dependencies
	depInstances, err := validateDependencies(m.deps, fieldsMap)
	if err != nil {
		panic(err)
	}

	// Step 4: Collect and sort middlewares
	mw, err = collectAndSortMiddlewares(depInstances)
	if err != nil {
		panic(err)
	}

	// Step 5: Wrap the handler
	h = wrapHandler(info, fieldsMap)

	return h, mw
}

func (m *Manager) GET(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).GET(path, h)
	return m
}

func (m *Manager) POST(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).POST(path, h)
	return m
}

func (m *Manager) PUT(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).PUT(path, h)
	return m
}

func (m *Manager) PATCH(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).PATCH(path, h)
	return m
}

func (m *Manager) DELETE(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).DELETE(path, h)
	return m
}

func (m *Manager) HEAD(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).HEAD(path, h)
	return m
}

func (m *Manager) OPTIONS(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).OPTIONS(path, h)
	return m
}

func (m *Manager) Any(path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).Any(path, h)
	return m
}

func (m *Manager) Handle(method, path string, handler any) *Manager {
	h, mw := m.prepareHandler(handler)
	m.r.Group("", mw...).Handle(method, path, h)
	return m
}
